### ISSUE TITLE
Omega 运行过程中遇到的几个问题

### ISSUE THREAD

**Issue by teleping** [zillionare/omega#1]
安装、运行omega过程中碰到的几个问题：

**1. 系统平台问题**

由于项目运行依赖fcntl、termios等python库，windows平台下没有好的支持，需要在Linux环境下运行。

Windows系统，可以使用Win10下的WSL(适用于 Linux 的 Windows 子系统)，参考如下：

[适用于 Linux 的 Windows 子系统安装指南 (Windows 10)](https://docs.microsoft.com/zh-cn/windows/wsl/install-win10)
[安装和设置 Windows 终端](https://docs.microsoft.com/zh-cn/windows/terminal/get-started)
[比较 WSL 1 和 WSL 2](https://docs.microsoft.com/zh-cn/windows/wsl/compare-versions)
[Windows下如何构建Python开发环境](https://zhuanlan.zhihu.com/p/138005979)

**2. python版本问题**

omega项目中部分代码用到了python3.8 的新语法，需要python版本在3.8以上。

**3. 项目安装**

omega 项目包含了 cfg4py，pyemit，zillionare-omicron 等依赖，需要另外安装：zillionare-omega-adaptors-jq

安装 omega 过程会出现 talib 包安装失败的问题，项目代码似乎没有用到，可直接将项目目录下setup.py 文件中 requirments 列表中的talib项删掉进行解决。

**4. 配置修改**

找到以下文件如下代码，修改对应配置目录地址：omega/omega/core/__init__.py

```
def get_config_dir():
    if os.environ[cfg4py.envar] == 'PRODUCTION':
        _dir = path.expanduser('~/zillionare/omega/config')
    elif os.environ[cfg4py.envar] == 'TEST':
        _dir = path.expanduser('~/.zillionare/omega/config')
    else:
        _dir = path.normpath(path.join(path.dirname(__file__), '../config'))

    sys.path.insert(0, _dir)
    return _dir
```

运行时需要设置部署环境变量：\_\_cfg4py_server_role\_\_，值为以下其中之一：'PRODUCTION', 'TEST', 'DEV'
例：` export __cfg4py_server_role__=DEV`

然后修改对应的配置文件，如：dev.yaml，修改其中redis、quotes_server 等地址信息。

**5. 项目运行**

安装成功后，可以运行命令：

启动项目： omega start
停止项目： omega stop
启动 jobs： omega start jobs
查看状态：omega status
更多命令：omega -h

**Comment by zillionare** [comment]
talib已移除。
将在文档的安装部分加入上述说明

**Comment by zillionare** [comment]
1. 已发行docker-compose版本，解决了平台问题
2. 仅支持py3.8
