### ISSUE TITLE
为市值数据增加同步任务

### ISSUE THREAD

**Issue by zillionare** [zillionare/omega#2]
**Is your feature request related to a problem? Please describe.**
Omega 0.5发布之后，可以获取市值数据。市值数据从上游服务器获取，并保存在数据库中。但是，并没有增加daily job去自动同步市值数据。

**Describe the solution you'd like**
增加一个daily job到jobs进程中，每天开盘前自动同步前一天的市值数据。

**Comment by henrycs** [comment]
already implemented in current version.
